/**
* Prayer Times API
* Prayer Times API
*
* OpenAPI spec version: v1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.PrayerTime

/**
 * 
 * @param &#x60;data&#x60; 
 */
data class MonthlyPrayerTimes (

    val `data`: kotlin.Array<PrayerTime>? = null
) {
}