/**
* Prayer Times API
* Prayer Times API
*
* OpenAPI spec version: v1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import com.squareup.moshi.JsonClass


/**
 * 
 * @param fajr 
 * @param sunrise 
 * @param dhuhr 
 * @param asr 
 * @param maghrib 
 * @param isha 
 * @param hijri 
 * @param gregorian 
 */

@JsonClass(generateAdapter = true) // https://stackoverflow.com/a/58662289/1766716
data class PrayerTime (

    val fajr: kotlin.String,
    val sunrise: kotlin.String,
    val dhuhr: kotlin.String ,
    val asr: kotlin.String,
    val maghrib: kotlin.String ,
    val isha: kotlin.String,
    val hijri: kotlin.String,
    val gregorian: kotlin.String
) {
}