/**
* Prayer Times API
* Prayer Times API
*
* OpenAPI spec version: v1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param fajr 
 * @param sunrise 
 * @param dhuhr 
 * @param asr 
 * @param maghrib 
 * @param isha 
 * @param hijri 
 * @param gregorian 
 */
data class PrayerTime (

    val fajr: kotlin.String? = null,
    val sunrise: kotlin.String? = null,
    val dhuhr: kotlin.String? = null,
    val asr: kotlin.String? = null,
    val maghrib: kotlin.String? = null,
    val isha: kotlin.String? = null,
    val hijri: kotlin.String? = null,
    val gregorian: kotlin.String? = null
) {
}